# Generated by Django 3.2.13 on 2022-06-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(error_messages={'required': 'Enter Full Name'}, max_length=50),
        ),
    ]
