# Generated by Django 3.2.13 on 2022-06-23 07:14

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chargering_Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=80)),
                ('customer_mobile_no', models.IntegerField()),
                ('customer_id', models.IntegerField(unique=True)),
                ('city', models.CharField(max_length=255)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('total_time', models.CharField(max_length=100)),
                ('consume_power', models.CharField(max_length=200)),
            ],
        ),
    ]
