# Generated by Django 3.2.13 on 2022-06-23 06:11

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charger_Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charger_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=255)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('charger_id', models.IntegerField(unique=True)),
                ('charger_photo', models.ImageField(upload_to='Charger')),
                ('on_off', models.BooleanField(default=False)),
            ],
        ),
    ]
